### ISSUE TITLE
CMakeLists: SpectrumChartD3.min.index.js

### ISSUE THREAD

**Issue by jpbrodsky** [sandialabs/SpecUtils#1]
https://github.com/sandialabs/SpecUtils/blob/fb85855eaa11763f06c52bb3c4a767761264aa5b/CMakeLists.txt#L175

This line refers to a file not present in the repository.

**Comment by wcjohns** [comment]
Whoops, this was actually a non-necessary (or useful) file; removed in commit
#173d4df .  Thanks!
