### ISSUE TITLE
Compiling from source with Mac

### ISSUE THREAD

**Issue by mattmar2410** [sandialabs/SpecUtils#33]
Hi there, I am trying to compile from source on a Mac. I got the following error after the following two commands:
`$ cmake -DBUILD_CAMBIO_COMMAND_LINE=ON -DBUILD_CAMBIO_GUI=OFF -DBOOST_ROOT=/path/to/boost ..`
`$ make -j8`

Error:
/Users/<user>/repos/cambio/src/CommandLineUtil.cpp:2176:16: error: no member named 'keep_energy_cal_variant' in 'SpecUtils::SpecFile'
          info.keep_energy_cal_variant( prefered_variant );

In SpecUtils, it seems to be keep_energy_cal_variants not keep_energy_cal_variant, but can you please advise? 

Thanks!

**Comment by wcjohns** [comment]
Hi, it looks like you were maybe using a newer version of SpecUtils than the code had been updated for.
I just updated the submodule reference to the latest SpecUtils, and made a few small fixes to make Cambios command-line code compile with it, in commit [fee06ca](https://github.com/sandialabs/cambio/commit/fee06ca73c58fadf0c4c3b8e10b6b7a227066c26).

Please let me know if this doesn't fix things for you,
  -will
